/* empty css                           */import { c as createAstro, a as createComponent, r as renderTemplate, m as maybeRenderHead, d as renderComponent, f as renderTransition } from '../astro_96dc6b5b.mjs';
import 'clsx';
import { c as create_ssr_component, v as validate_component, B as Button, C as CldImage } from './credits_3294e4e1.mjs';
/* empty css                           */
/* src/components/ButtonAmazon.svelte generated by Svelte v4.2.0 */

const ButtonAmazon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let buttonClass;
	let { fullWidth = false } = $$props;
	let { disabled = true } = $$props;
	let { size = "xl" } = $$props;
	if ($$props.fullWidth === void 0 && $$bindings.fullWidth && fullWidth !== void 0) $$bindings.fullWidth(fullWidth);
	if ($$props.disabled === void 0 && $$bindings.disabled && disabled !== void 0) $$bindings.disabled(disabled);
	if ($$props.size === void 0 && $$bindings.size && size !== void 0) $$bindings.size(size);
	buttonClass = `${fullWidth && "w-full"} no-underline`;

	return `${validate_component(Button, "Button").$$render(
		$$result,
		{
			href: "https://www.amazon.com/dp/B0C9VVS9KX?ref=myi_title_dp",
			target: "_blank",
			color: "primary",
			size,
			class: buttonClass
		},
		{},
		{
			default: () => {
				return `<svg class="mr-3" style="color: white" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 512 512"><title>ionicons-v5_logos</title><path d="M48.48,378.73a300.52,300.52,0,0,0,152.89,95.92,262.57,262.57,0,0,0,159.3-17.25,225.52,225.52,0,0,0,66.79-47,6.36,6.36,0,0,0-2-8.53,11.76,11.76,0,0,0-8-.05,401.92,401.92,0,0,1-116.55,39.34,358.13,358.13,0,0,1-127.29-8.83,446.73,446.73,0,0,1-119.1-60.49,5,5,0,0,0-6.06,6.9Z" fill="white"></path><path d="M387.15,388.44a168.11,168.11,0,0,1,48.94-2.23l.67.13a10,10,0,0,1,7.37,12.05A204.71,204.71,0,0,1,429,444.47a2.55,2.55,0,0,0,1.66,3.18,2.51,2.51,0,0,0,2.23-.37A83.31,83.31,0,0,0,464,382.86a12.44,12.44,0,0,0-10.22-13.22A95.75,95.75,0,0,0,384.91,384a2.55,2.55,0,0,0-.57,3.55A2.52,2.52,0,0,0,387.15,388.44Z" fill="white"></path><path d="M304.24,324.92a164,164,0,0,1-28.92,25.3A135.16,135.16,0,0,1,208.63,369a99.49,99.49,0,0,1-57.49-19.85,97.25,97.25,0,0,1-27.36-100.28,112.35,112.35,0,0,1,65.3-69.06,367.67,367.67,0,0,1,104.7-15.55V127A37.82,37.82,0,0,0,261,94.72a59.9,59.9,0,0,0-31.17,4.08,48.89,48.89,0,0,0-27.13,34.67,12,12,0,0,1-12.58,6.72l-50.9-4.5a11.38,11.38,0,0,1-8.38-10.16,103.66,103.66,0,0,1,36.61-63.45A143.86,143.86,0,0,1,257.85,32a146.24,146.24,0,0,1,84.27,27.67,86.82,86.82,0,0,1,30.7,70.22V258.8a84.46,84.46,0,0,0,8,31.28l15.87,23.23a13,13,0,0,1,0,11.23L349.7,364.25a12.5,12.5,0,0,1-12.68-.44A244.84,244.84,0,0,1,304.24,324.92Zm-10.6-116.83a257.68,257.68,0,0,0-44,2.89A63,63,0,0,0,208,242.54a63,63,0,0,0,3.07,54,40.6,40.6,0,0,0,47.11,12.19,78.61,78.61,0,0,0,35.46-55.58V208.09" fill="white"></path></svg>
	Buy on Amazon`;
			}
		}
	)}`;
});

const $$Astro = createAstro();
const $$Hero = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Hero;
  return renderTemplate`${maybeRenderHead()}<section><div class="flex flex-row flex-wrap font-[Itim]"><div class="p-4 md:basis-7/12" role="button" tabindex="0"><a href="/products/hunnie-bunnys-garden">${renderComponent($$result, "CldImage", CldImage, { "width": 1616, "height": "100%", "aspectRatio": 1413 / 983, "class": "rounded-lg w-full", "src": "hunnie-bunnys-garden-table", "alt": "book mockup cover", "quality": 75, "loading": "eager", "data-astro-transition-scope": renderTransition($$result, "42rhxlxx", "", "hunnie-bunnys-garden") })}<div class="self-stretch text-center text-gray-900 md:text-xl lg:text-2xl text-xl p-3"><p class="mb-2">
Hunnie Bunny’s Garden is a delightful blend of entertainment and education that provides endless opportunities for learning and discovery.
</p><p class="mb-2">This charming story is a wonderful testament to the beauty of nature and the joy that gardening can bring.</p><p class="pt-3 text-shadow-black-xs text-black">Add Hunnie Bunny’s Garden to your child’s library today!</p></div></a></div><div class="p-4 basis-full md:basis-5/12 flex flex-col justify-start items-center"><div class="md:mt-[70px] xl:mt-[90px] text-center text-black text-xl lg:text-2xl xl:text-3xl font-normal mb-10 md:mb-20"><div class="text-center text-black text-3xl lg:text-4xl xl:text-5xl font-normal mb-2 underline">Hunnie Bunny's Garden</div><mark class="px-2 bg-[#B9D6B8] rounded">Available Now</mark></div>${renderComponent($$result, "ButtonAmazon", ButtonAmazon, {})}${renderComponent($$result, "CldImage", CldImage, { "width": 1420, "height": "100%", "aspectRatio": 2100 / 1500, "style": "scale:1.25", "src": "hunnie-bunny-reading-book", "alt": "hunnie bunny reading", "class": "mt-16" })}</div></div></section>`;
}, "/Users/json/Projects/SimpleReadsBooks/SimpleReadsBooks/src/pages/home/hero.astro", "self");

const $$file = "/Users/json/Projects/SimpleReadsBooks/SimpleReadsBooks/src/pages/home/hero.astro";
const $$url = "/home/hero";

const hero = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	default: $$Hero,
	file: $$file,
	url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

export { $$Hero as $, ButtonAmazon as B, hero as h };
